# Generated by Django 3.1.4 on 2020-12-31 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('stroke', models.CharField(blank=True, max_length=20, null=True)),
                ('translation', models.CharField(default='N/A', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unnamed group', max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroke', models.CharField(blank=True, max_length=20, null=True)),
                ('translation', models.CharField(default='N/A', max_length=200, unique=True)),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wordgroup')),
            ],
        ),
    ]
