# Generated by Django 3.1.4 on 2021-01-02 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levels',
            name='level',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='stroke',
        ),
        migrations.RemoveField(
            model_name='levels',
            name='translation',
        ),
        migrations.AddField(
            model_name='levels',
            name='name',
            field=models.CharField(default='unnamed group', max_length=100),
        ),
        migrations.AddField(
            model_name='levels',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
