# Generated by Django 3.1.4 on 2021-01-02 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210102_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levels',
            name='parent',
        ),
    ]
