# Generated by Django 3.1.4 on 2021-01-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210104_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordgroup',
            name='trash',
            field=models.BooleanField(default=False),
        ),
    ]
